name: skylit-photography
region: nyc
services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      # Required Environment Variables
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: SESSION_SECRET
        value: YOUR_SESSION_SECRET_HERE
        type: SECRET
      - key: FRONTEND_URL
        value: ${APP_URL}
      # Google OAuth (OPTIONAL - Currently disabled)
      # Uncomment these lines when you're ready to enable Google sign-in
      # - key: GOOGLE_CLIENT_ID
      #   value: YOUR_GOOGLE_CLIENT_ID
      #   type: SECRET
      # - key: GOOGLE_CLIENT_SECRET
      #   value: YOUR_GOOGLE_CLIENT_SECRET
      #   type: SECRET
      # - key: GOOGLE_CALLBACK_URL
      #   value: ${APP_URL}/api/auth/google/callback

